### ISSUE TITLE
Fails to build with the latest nightly.

### ISSUE THREAD

**Issue by PurpleMyst** [teloxide/dptree#22]
As per the title, building fails with an error related to the unstable feature `closure_track_caller` ever since `nightly-2022-11-18` (found by cargo-bisect-rustc).

**Comment by robertpauson** [comment]
I've added `#![feature(closure_track_caller)]` to the file that fails to build and issue persists

**Comment by PurpleMyst** [comment]
Seems to be an upstream regression in nightly, it's already reported as an issue on the rust repository. Only thing to do for now is to stay on the latest working nightly until everything works again, therefore this issue should probably be closed as it does not concern dptree directly.

**Comment by WaffleLapkin** [comment]
For reference this is the issue: https://github.com/rust-lang/rust/issues/105134
