### ISSUE TITLE
Make crate never panic

### ISSUE THREAD

**Issue by AbstractiveNord** [teloxide/dptree#24]
Is it possible to remove panics from crate at all?
Also may be useful to try using no_panic! macro.

**Comment by WaffleLapkin** [comment]
This is not descriptive enough. What is your problem, how do you want to it be solved?...

**Comment by AbstractiveNord** [comment]
Currently dptree crate may panic, at least in case of dependency management. Usually I cover my code with no_panic! macro, as guarantee. I want to check, is it possible to turn all dptree crate possible error into compile-time, which makes no panic guarantee possible to be applied.

**Comment by WaffleLapkin** [comment]
> I want to check, is it possible to turn all dptree crate possible errors into compile-time

No, currently you can't check if a type is in a list of types at compile time.

**Comment by AbstractiveNord** [comment]
> > I want to check, is it possible to turn all dptree crate possible errors into compile-time
> 
> No, currently you can't check if a type is in a list of types at compile time.

Kinda sad. Thanks for answers!

**Comment by WaffleLapkin** [comment]
There is a plan to move panics to initialization, so if your app started, then it won't panic anymore. #23 implements this.
