### ISSUE TITLE
Got lost trying to understand how chain works

### ISSUE THREAD

**Issue by zim32** [teloxide/dptree#25]
Hello. Thanks for this lib. I am playing with it and got lost in my understanding how it works..
I have three handlers, every handler returns `ControlFlow::Continue(())`

In this scenario only First and Second handlers are called, no matter how I nest them:

Plain chaining:

```
    let root = dptree::entry()
        .branch(first_handler).chain(second_handler).chain(third_handler)
    ;
```

Nested chaining:

```
    let root = dptree::entry()
        .branch(first_handler).chain(second_handler.chain(third_handler))
    ;
```

In both cases I got:

```
First handler called
Second handler called
```

Why my third handler is not called?

**Comment by WaffleLapkin** [comment]
Can you provide definitions of the handlers? And also what are you trying to achieve?

**Comment by zim32** [comment]
Ah i am doing something stupid I guess. I need to call continuation()

**Comment by WaffleLapkin** [comment]
why are you even using `from_fn`? it's quite a "low level" function, you are not supposed to need it, usually...

but yeah, you need to call continuation on order to execute handlers next in the chain

**Comment by zim32** [comment]
Yeah this is how I learn things. Go from low level ) Anyway thanks for quick response. I guess I found a problem
