### ISSUE TITLE
Alternative to `dptree::map` that replaces the input

### ISSUE THREAD

**Issue by PurpleMyst** [teloxide/dptree#9]
As per the title, It'd be great to have a version of `dptree::map` (and `dptree::map_async` of course) that replaced the input instead of adding on to it.

To avoid an XY problem, here's what I'm trying to do:

1. Have my chain of responsibility
2. Add, at the end of the chain, something that gets the `Result<()>` of everything that's come before and handles it, potentially logging in to the user or something of the sort.

Thank you all in advance. I'd be willing to help in implementing this if given a little guidance.

**Comment by Hirrolot** [comment]
Hi! What do you mean by "replacing the input instead of adding on to it"?

**Comment by PurpleMyst** [comment]
Basically right now `map`:

1. Runs the given function;
2. Stores that function's result into the `DependencyMap`.

I'd like a function that:

1. Runs the given function;
2. Clears the `DependencyMap`;
3. Inserts the function's result into the now-empty `DependencyMap`.

**Comment by Hirrolot** [comment]
Yes, now I understand. However, why is this needed?

> Add, at the end of the chain, something that gets the Result<()> of everything that's come before and handles it, potentially logging in to the user or something of the sort.

Since it is at the end of the chain, no dependencies will be passed forwards.

**Comment by Hirrolot** [comment]
Closed due to inactivity.
